%[ER: 70]% Added approximate floating point number check

diff --git a/autoconf_share/assay b/autoconf_share/assay
--- a/autoconf_share/assay
+++ b/autoconf_share/assay
@@ -215,13 +215,44 @@
   sed -e '/^>>>/,/^<<</d' ${1}_tmp.out2 > ${1}_tmp.out
 
 # Compare with the expected output.
-  if $CAT $1.out | sed -e 's/>>>.*<<<//' | sed -e '/^>>>/,/^<<</d' | diff ${1}_tmp.out -
+  $CAT $1.out | sed -e 's/>>>.*<<<//' | sed -e '/^>>>/,/^<<</d' > ${1}_tmp_orig.out
+  if diff ${1}_tmp.out ${1}_tmp_orig.out
   then
      echo "PASS (output verified): $*"
      STATUS=0
      exit
-  else
+  fi
+
+# Not fully equal, check if equal except for numbers.
+# Replace for this purpose all numbers by x.
+  sed -e 's/[+-]\?\(\(\([0-9]\+\)\|\([0-9]*\.\?[0-9]*\)\)\(e[+-]\?[0-9]\+\)\?\)/x/g' ${1}_tmp.out > ${1}_tmp.out2
+  sed -e 's/[+-]\?\(\(\([0-9]\+\)\|\([0-9]*\.\?[0-9]*\)\)\(e[+-]\?[0-9]\+\)\?\)/x/g' ${1}_tmp_orig.out > ${1}_tmp_orig.out2
+  diff ${1}_tmp.out2 ${1}_tmp_orig.out2 > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
      echo "FAIL (output not verified): $*"
      STATUS=2
      exit
   fi
+
+# Okay, the non-numbers are equal.
+# Now check if all numbers are approximately equal.
+# First replace all non-numeric characters and single e.+- by a blank.
+# Remove blanks by a newline.
+  sed -e 's/[^-+.e0-9]/ /g' ${1}_tmp.out | sed -e 's/\(^\| \)[e.+-]\+\( \|$\)//g' | sed -e 's/^ \+//' -e 's/ \+$//' -e 's/ \+/\n/g' > ${1}_tmp.out2
+sed -e 's/[^-+.e0-9]/ /g' ${1}_tmp_orig.out | sed -e 's/\(^\| \)[e.+-]\+\( \|$\)//g' | sed -e 's/^ \+//' -e 's/ \+$//' -e 's/ \+/\n/g' > ${1}_tmp_orig.out2
+# Show the differences column-wise.
+  diff -y --suppress-common-lines ${1}_tmp.out2 ${1}_tmp_orig.out2 > ${1}_tmp_diff.out
+
+# Now loop through all differences and see if almost equal.
+  awk '{ a1=$1; if (a1<0) a1=-a1; a2=$3; if (a2<0) a2=-a2; if (a1>1e-20 || a2>1e-20) if ((a1>a2 && a1-a2> 1e-5*a1) || (a2>a1 && a2-a1> 1e-5*a2)) print "float diff>1e-5:",a1,a2 }' ${1}_tmp_diff.out > ${1}_tmp_diff.out2
+  if [ -s ${1}_tmp_diff.out2 ]
+  then
+     $CAT ${1}_tmp_diff.out2
+     echo "FAIL (large floating point discrepancies): $*"
+     STATUS=2
+     exit
+  fi
+  echo "PASS (small floating point discrepancies): $*"
+  STATUS=0
+  exit
