Added the possibility of a recursive bootstrap, configure, and make

diff --git a/autoconf_share/bootstrap b/autoconf_share/bootstrap
--- a/autoconf_share/bootstrap
+++ b/autoconf_share/bootstrap
@@ -27,17 +27,50 @@ if test $# != 1; then
   echo usage: bootstrap autoconf_share_dir
   exit 1
 fi
-set -x
+
+echo "Bootstrapping in `pwd`"
 
 # Make symlinks for ease of use.
 \rm -f autoconf_share lofarconf
 ln -s $1 autoconf_share
 ln -s $1/lofarconf lofarconf
 
-# Initialize auto tools
-aclocal -I $1 \
-&& libtoolize --force --copy \
-&& autoheader \
-&& automake --foreign --add-missing --copy \
-&& autoconf
+# Bootstrap recursively if a file lofarconf.in exists.
+# Get subdirectories from that file.
+lfr_lofarconf=0
+if [ -r lofarconf.in ]; then
+  lfr_lofarconf=1
+  # Get all subdirectories from lofarconf.in while removing comments.
+  subdirs=`sed lofarconf.in -e s/#.*$//g`
+  for subdir in $subdirs
+  do
+    if [ ! -d $subdir ]; then
+      echo " Error: subdirectory $subdir not found"
+      exit 2
+    fi
+    cd $subdir > /dev/null   # suppress possible cd output
+    if [ ! -r bootstrap ]; then
+      # Add an extra ../ to the autoconf_share paths.
+      sed ../bootstrap -e s%\.\./auto%\.\./\.\./auto%g > bootstrap
+      chmod +x bootstrap
+    fi
+    ./bootstrap || exit 2
+    cd .. > /dev/null
+  done
+fi
+
+# Initialize auto tools if configure.in exists.
+if [ -r configure.in ]; then
+  if test "$lfr_lofarconf" != 0; then
+    echo " Error: configure.in or lofarconf.in may exist, not both"
+  fi
+  set -x
+  aclocal -I $1 \
+  && libtoolize --force --copy \
+  && autoheader \
+  && automake --foreign --add-missing --copy \
+  && autoconf
+elif test "$lfr_lofarconf" = 0; then
+  echo " Warning: configure.in nor lofarconf.in found"
+fi
 
diff --git a/autoconf_share/lofarconf b/autoconf_share/lofarconf
--- a/autoconf_share/lofarconf
+++ b/autoconf_share/lofarconf
@@ -40,7 +40,7 @@ lfr_base=$lfr_root/autoconf_share
 # Exit if not found.
 lfr_result=`$lfr_base/findpkg -l`
 if [ $? != 0 ]; then
-  echo "Could not derive package from current build directory";
+  echo "Could not derive package from build directory $lfr_curdir";
   echo "The build directory should be in the source tree like"
   echo "      LOFAR/'package'/build/'variant'"
   echo "or in another tree like"
@@ -53,9 +53,14 @@ lfr_pkg=`echo $lfr_result | awk '{print $1}'`
 lfr_cmp=`echo $lfr_result | awk '{print $2}'`
 lfr_var=`echo $lfr_result | awk '{print $3}'`
 
-# The configure script for the package is in the same tree as
-# this script is in.
+# Get the directory of the configure files for the package.
 lfr_confdir=$lfr_root/$lfr_pkg;
+
+# If there is a file lofarconf.in, we have to configure recursively.
+if [ -r $lfr_confdir/lofarconf.in ]; then
+  $lfr_base/lofarconf_recur "$@" || exit 2
+  exit 0
+fi
 
 # Get the configure and make options from the variants file.
 # Look first for a host specific one; if not found, for a general one.
