%[ER: 70]% Fixed little buildsys problem; given some more output

diff --git a/autoconf_share/buildsys b/autoconf_share/buildsys
--- a/autoconf_share/buildsys
+++ b/autoconf_share/buildsys
@@ -104,6 +104,11 @@ if test "$pkgs" = ""; then
   exit 2
 fi
 
+echo ""
+echo 'Building PACKAGES="'"$pkgs"'"'
+echo '         VARIANTS="'"$variants"'"'
+echo ""
+
 # Build the system.
 date
 echo && echo ":::::: SYSTEM BUILD START" && echo
@@ -124,7 +129,7 @@ do
        && echo \
        && date \
        && ((mkdir -p $pkg/build/$var && cd $pkg/build/$var && \
-            lofarconf -norecursive "$prefixopt") || echo ":::::: ERROR") \
+            ../../lofarconf -norecursive "$prefixopt") || echo ":::::: ERROR") \
        && echo \
        && echo ":::::: FINISHED CONFIGURING VARIANT $var FOR PACKAGE $pkg" \
        && echo
diff --git a/autoconf_share/rub b/autoconf_share/rub
--- a/autoconf_share/rub
+++ b/autoconf_share/rub
@@ -305,17 +305,19 @@ done
 echo "Created lofarconf.in.private containing all these packages"
 pkgs=`cat lofarconf.in.private`
 
-echo "See rub.log for the cvs update/checkout details"
-egrep "^C " rub.log > greplog.tmp 2>&1
-if [ $? = 0 ]; then
-  echo "Error: there seem to be UPDATE CONFLICTS"
-  cat greplog.tmp
+if [ $update != 0 ]; then
+  echo "See rub.log for the cvs update/checkout details"
+  egrep "^C " rub.log > greplog.tmp 2>&1
+  if [ $? = 0 ]; then
+    echo "Error: there seem to be UPDATE CONFLICTS"
+    cat greplog.tmp
+    \rm -f greplog.tmp
+    exit 1
+  else
+    echo "There are no update conflicts"
+  fi
   \rm -f greplog.tmp
-  exit 1
-else
-  echo "There are no update conflicts"
 fi
-\rm -f greplog.tmp
 
 if [ "$variants" = "" ]; then
   echo "No build to be done"
