%[ER: 70]% Added option -confopt

diff --git a/autoconf_share/buildsys b/autoconf_share/buildsys
--- a/autoconf_share/buildsys
+++ b/autoconf_share/buildsys
@@ -34,14 +34,14 @@ if test "$1" = ""  -o  "$1" = "-h"  -o  "$1" = "--help"; then
   echo 'It does bootstrap, configure, make, check and install.'
   echo ''
   echo 'Run as:'
-  echo ' rub [-prefix] variants package1 [package2 ...]'
-  echo '  -prefix prefix  gives the prefix for the install directories.'
-  echo '  variants        gives the variants to do (e.g. gnu3_debug)'
-  echo '                  Separate multiple variants by whitespace and'
-  echo '                  enclose in quotes.'
-  echo '                  This info is shown if no variant is given.'
-  echo '  package1        is the name of the package to be built'.
-  echo '                  Multiple packages can be given separated by whitespace.'
+  echo ' buildsys [-confopt] variants package1 [package2 ...]'
+  echo '  -confopt confopt  gives optional configure options.'
+  echo '  variants          gives the variants to do (e.g. gnu3_debug)'
+  echo '                    Separate multiple variants by whitespace and'
+  echo '                    enclose in quotes.'
+  echo '                    This info is shown if no variant is given.'
+  echo '  package1          is the name of the package to be built'.
+  echo '                    Multiple packages can be given separated by whitespace.'
   echo ' If no packages are given, the contents of lofarconf.in.private'
   echo ' or lofarconf.in are used.'
   echo ''
@@ -53,21 +53,21 @@ pgmpath=`dirname $0`
 pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`
 
 # Handle possible options.
-prefixopt=
+confopt=
 while [ 1 = 1 ]
 do
-  # Get possible prefix option.
-  # It can be given as -prefix or --prefix, optionally using =.
+  # Get possible configure option.
+  # It can be given as -confopt or --confopt, optionally using =.
   opt="$1"
   case "$opt" in
-  --prefix*)
+  --confopt*)
     opt=`echo "$opt" | sed -e 's/-//'`
     ;;
   *)
     ;;
   esac
   case "$opt" in
-  -prefix*)
+  -confopt*)
     shift
     val=`echo $opt | sed -e 's/.*=//'`
     if test "$val" = "$opt"; then
@@ -76,7 +76,7 @@ do
     else
       opt="$val"
     fi
-    prefixopt="--prefix=$opt"
+    confopt="$opt"
     ;;
   *)
     break
@@ -107,6 +107,7 @@ fi
 echo ""
 echo 'Building PACKAGES="'$pkgs'"'
 echo '         VARIANTS="'$variants'"'
+echo '         confopt="'$confopt'"'
 echo ""
 
 # Build the system.
@@ -129,7 +130,7 @@ do
        && echo \
        && date \
        && ((mkdir -p $pkg/build/$var && cd $pkg/build/$var && \
-            ../../lofarconf -norecursive "$prefixopt") || echo ":::::: ERROR") \
+            ../../lofarconf -norecursive $confopt) || echo ":::::: ERROR") \
        && echo \
        && echo ":::::: FINISHED CONFIGURING VARIANT $var FOR PACKAGE $pkg" \
        && echo
