%[ER: 70]% Check in a better way if configure fails

diff --git a/autoconf_share/lofarconf b/autoconf_share/lofarconf
--- a/autoconf_share/lofarconf
+++ b/autoconf_share/lofarconf
@@ -139,8 +139,13 @@ if [ -e lofar_config.h ]; then
   mv lofar_config.h lconfig.h.lofarsav
 fi
 echo $lfr_confdir/configure $opts
-eval $lfr_confdir/configure $opts || exit 2
+eval $lfr_confdir/configure $opts
+if [ "$?" != 0 ]; then
+  echo "Error during configure"
+  exit 2
+fi
 # Include config.h in lofar_config.h.
+echo "lofarconf: creating lofar_config.h"
 echo "/* Generated by lofarconf */" > lconfig.h
 echo "" >> lconfig.h
 echo "#ifndef LOFAR_CONFIG_H" >> lconfig.h
