BugID: 556 Added flag -contbuild to avoid a lot of rebuilding

diff --git a/autoconf_share/rub b/autoconf_share/rub
--- a/autoconf_share/rub
+++ b/autoconf_share/rub
@@ -78,8 +78,10 @@ install=2
 distcheck=0
 rpm=0
 update=1
+contbuild=0
 system=0
 recur=1
+
 verstype=
 pkgfound=0
 help=0
@@ -177,6 +179,12 @@ do
   elif [ "$1" = -noconfopt ]; then
     shift
     confopt=""
+  elif [ "$1" = -contbuild ]; then
+    shift
+    contbuild=1
+  elif [ "$1" = -nocontbuild ]; then
+    shift
+    contbuild=0
   elif [ "$1" = -clean ]; then
     shift
     clean=1
@@ -290,7 +298,7 @@ if [ $help = 1 ]; then
   echo 'Run as:'
   echo ' rub [-cvs cvs-command] [-update] [-updq string] [-r<cvstag>]'
   echo '     [-recur[sive]] [-release=option] [-build variants]]'
-  echo '     [-system] [-conf] [-confopt string]' [-j<option>]
+  echo '     [-system] [-conf] [-confopt string] [-j<option>] [-contbuild]'
   echo '     [-[dist]clean] [-make] [-check] [-install] [-distcheck] [-rpm]'
   echo '     package1 [-v<version>] [...]'
   echo ''
@@ -327,6 +335,11 @@ if [ $help = 1 ]; then
   echo '                    Default is -noconf.'
   echo '  -confopt string   configure options.'
   echo '  -j<option>        Option for a parallel make. Default is -noj.'
+  echo '  -contbuild        Continue from the previous build run; thus start'
+  echo '                    the build at the package that failed last time.'
+  echo '                    Successfully built packages are logged in file'
+  echo '                    build.result.<variant>.   It forces -noupdate.'
+  echo '                    Default is -nocontbuild'.
   echo '  -clean            indicates that all build/<variant> directories'
   echo '                    will be cleaned in order to start a clean build.'
   echo '                    Default is -noclean.'
@@ -453,6 +466,11 @@ done
 # Add the possibly last package.
 if [ "$pkg" != "" ]; then
   PKGS="$PKGS $pkg#-v"
+fi
+
+# Do not update if contbuild is given.
+if [ $contbuild = 1 ]; then
+  update=0;
 fi
 
 # Check if in correct directory.
@@ -607,20 +625,31 @@ if [ $rpm = 1 ]; then
 fi
 
 # Build all variants.
-\rm -f build.log
-touch build.log
+if [ $contbuild = 0 ]; then
+  # Start fresh, so delete results from previous builds.
+  \rm -f build.log build.result.*
+  touch build.log
+fi
 for variant in $variants
 do
   echo "Building packages in build/$variant ..."
   echo "" >> build.log
   echo "***** Building packages in build/$variant ..." >> build.log
+  touch build.result.$variant
   for pkg in $pkgs
   do
+    if [ $contbuild = 1 ]; then
+      fgrep "$pkg " build.result.$variant >& /dev/null
+      if [ $? = 0 ]; then
+        echo "  package $pkg will not be built; already done in previous run"
+        continue
+      fi
+    fi
     echo "  building package $pkg ..."
     echo "" >> build.log
     echo " *** Building package $pkg ***" >> build.log
     echo "(cd $pkg && mkdir -p build/$variant && $bootcmd cd build/$variant && $confcmd $premake $mainmake $postmake;)" >> build.log
-    eval "(cd $pkg && mkdir -p build/$variant && $bootcmd cd build/$variant && $confcmd $premake make $postmake;)" >> build.log 2>&1
+    eval "(cd $pkg && mkdir -p build/$variant && $bootcmd cd build/$variant && $confcmd $premake make $postmake && echo $pkg '#' `date` >> $curwd/build.result.$variant;)" >> build.log 2>&1
     status=$?
     if [ "$status" != 0 ]; then
       echo " Error during build (see build.log for details)"
